/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Arrivals: typeof import('./components/Arrivals.vue')['default']
    ArrivalsTable: typeof import('./components/ArrivalsTable.vue')['default']
    LoadingState: typeof import('./components/LoadingState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./components/Schedule.vue')['default']
    StationList: typeof import('./components/StationList.vue')['default']
  }
}
